name: docker

on:
  pull_request:
  #    paths:
  #      - '.requirements'
  #      - 'install-build-deps.sh'
  #      - 'Dockerfile'
  push:
    branches:
      - master
#    paths:
#      - '.requirements'
#      - 'install-build-deps.sh'
#      - 'Dockerfile'

jobs:
  eksctl-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get docker hash version
        run: echo ::set-env name=IMAGE_HASH::$(cat .docker/image_tag)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sayboras/eksctl-build
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "${{ env.IMAGE_HASH }}"
